### ISSUE TITLE
fails to install on linux and osx

### ISSUE THREAD

**Issue by madmongo1** [xJoshx/secr#1]
76937 warn optional Skipping failed optional dependency /chokidar/fsevents:
76938 warn notsup Not compatible with your operating system or architecture: fsevents@1.0.12
76939 warn optional Skipping failed optional dependency /browser-sync/chokidar/fsevents:
76940 warn notsup Not compatible with your operating system or architecture: fsevents@1.0.12
76941 warn secr-assignment@1.0.0 No repository field.
76942 verbose stack Error: secr-assignment@1.0.0 postinstall: `typings install`
76942 verbose stack spawn ENOENT
76942 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
76942 verbose stack     at emitTwo (events.js:87:13)
76942 verbose stack     at ChildProcess.emit (events.js:172:7)
76942 verbose stack     at maybeClose (internal/child_process.js:821:16)
76942 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
76943 verbose pkgid secr-assignment@1.0.0
76944 verbose cwd /home/rhodges/interview/xJoshx
76945 error Linux 4.4.0-22-generic
76946 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
76947 error node v4.2.6
76948 error npm  v3.5.2
76949 error file sh
76950 error code ELIFECYCLE
76951 error errno ENOENT
76952 error syscall spawn
76953 error secr-assignment@1.0.0 postinstall: `typings install`
76953 error spawn ENOENT
76954 error Failed at the secr-assignment@1.0.0 postinstall script 'typings install'.
76954 error Make sure you have the latest version of node.js and npm installed.
76954 error If you do, this is most likely a problem with the secr-assignment package,
76954 error not with npm itself.
76954 error Tell the author that this fails on your system:
76954 error     typings install
76954 error You can get information on how to open an issue for this project with:
76954 error     npm bugs secr-assignment
76954 error Or if that isn't available, you can get their info via:
76954 error     npm owner ls secr-assignment
76954 error There is likely additional logging output above.
76955 verbose exit [ 1, true ]

**Comment by xJoshx** [comment]
It should be working now, I've updated the build process and now runs perfectly, as well I've updated the package.json to get all the dependencies. If this error happens agains, please reopen this issue or open a new one :).
